server:
  port: 8082

spring:
  application:
    name: encryption-service

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:encryptiondb}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/   # Eureka server URL
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}