package com.encryption_decryption_microservices.encryption_microservices_encryption_service.service;

import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.DecryptionRequestDto;
import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.DecryptionResponseDto;
import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.EncryptionRequestDto;
import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.EncryptionResponseDto;

import java.util.List;

public interface EncryptionService {
    EncryptionResponseDto encryptText(EncryptionRequestDto request);

    DecryptionResponseDto decryptText(DecryptionRequestDto request);

    List<EncryptionResponseDto> getUserHistory(Long userId);
}
