package com.encryption_decryption_microservices.encryption_microservices_encryption_service.service;

import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.DecryptionRequestDto;
import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.DecryptionResponseDto;
import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.EncryptionRequestDto;
import com.encryption_decryption_microservices.encryption_microservices_encryption_service.dto.EncryptionResponseDto;

public interface EncryptionService {
    EncryptionResponseDto encryptText(EncryptionRequestDto encryptionRequestDto);
    DecryptionResponseDto decryptionText(DecryptionRequestDto decryptionRequestDto);
}
